- Pos: sensor - pos1
  Rectangle:
    - x: 1.0
      y: 5.0
      z: 0.0
    - x: 3.0
      y: 0.0
      z: 0.0
    - x: 5.0
      y: 0.0
      z: 0.0
    - x: 5.0
      y: 3.0
      z: 0.0
    - x: 8.0
      y: 0.0
      z: 0.0

# - Pos: sensor - pos1
#   Rectangle:
#     - x: 3.0
#       y: 5.0
#       z: 0.0
#     - x: 3.0
#       y: 6.0
#       z: 0.0
#     - x: 5.0
#       y: 4.0
#       z: 0.0
#     - x: 8.0
#       y: 6.0
#       z: 0.0
#     - x: 3.0
#       y: 7.0
#       z: 0.0













